# Site settings
title: Webify Africa website
description: >- # this means to ignore newlines until "baseurl:"
  A description of my site
baseurl: "" # the base hostname & protocol for your site
url: "https://abishaimwanja.github.io/webifyafrica.github.io" # the base URL for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-primer # or your chosen theme

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from being processed
exclude:
  - README.md
  - LICENSE

# Other configurations
author: Abishai Mwanja
